#*************************#
#                         #
#         Options         #
#                         #
#*************************#

options:
	prefix: &7[&cPunishment-&aDEV]
	permission_message: &cNincs jogod ehhez!
	main_command_permission: punishment.use
	ban_permission: punishment.ban
	unban_permission: punishment.unban
	kick_permission: punishment.kick
	main_command_usage: &cHasználat /punishmnet help
	ban_usage:  &cHasználat /ban
	unban_usage: &cHasználat /unban
	kick_usage: &cHasználat /kick
	forver_ban_message: Bannolva lettél
	ban_message: Bannolva lettél
	unban_message: Unbannolva lettél
	kick_message: Kickelve lettél
	discordbot_name: SK-test
	discordbot_TOKEN: NjEzMjc3NDU1NzA0MTI5NTU3.XVulIw.3bQPquk7LksRgfm5g65dhgf8ESY

	version: 1.0.4
	checkUpdates: false
	configpath: plugins/Punishment-dev/config.yml
	listpath: plugins/Punishment-dev/lista.yml
	skript: Punishment-Skript\Punishment_dev
	updatelog: https://github.com/InternalGaming02/BanGUI-Skript/releases
	url: https://pastebin.com/raw/RbzMPk3L
	mainglass: white stained glass pane

#*************************#
#                         #
#      Tab completer      #
#                         #
#*************************#

on tab complete of "/punishment", "/punish" and "/p":
	set tab completions for position 1 to "help", "reload", "skriptreload", "file", "update" and "github"
	if tab arg-1 is "update":
		set tab completions for position 2 to "check", "log" and "download"

#*************************#
#                         #
#      Update manager     #
#                         #
#*************************#

on join:
	if {@checkUpdates} is true:
		set {_ver} to line 1 from url "{@url}"
		if "%{_ver}%" isn't "{@version}":
			if player has permission "punishment.update.notify":
				message "&7---------------------------------------"
				message "&bÚj verzió érhető el: &6%{_ver}%"
				message "&bAz updatokért nézd meg a Github oldalt!"
				message "&6{@updatelog}"
				message "&7---------------------------------------"			

#*************************#
#                         #
#        Functions        #
#                         #
#*************************#

function helpJSON(p : player):

	send "&7---------------------&bSegítség&7---------------------" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p help>/punishment help<reset> - &7 Ennek a menünek a megnyítása" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p reload>/punishment reload<reset> - &7 Config/Skript újratötlése" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p update>/punishment update<reset> - &7 Frissítések" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><link:https://github.com/InternalGaming02/BanGUI-Skript>/punishment github<reset>- &7 Github" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/ban >/ban [játékosnév] [idő] [ok]<reset>- &7Játékos kitiltása" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/unban>/unban [játékosnév] [ok]<reset> - &7Játékos kitiltásának feloldása" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/kick>/kick [játékosnév] [ok]<reset> - &7Játékos kirúgása" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/mute>/mute [játékosnév] [idő] [ok]<reset> - &7Játékos némítása" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/report>/report [játékosnév]<reset> - &7Játékos jelentése" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/reportdc >/reportdc [játékosnév]<reset>- &7Játékos jelentése discordon" to {_p}
	send "&7-------------------------------------------------" to {_p}

function updateHelp(p : player):
	set {_ver} to line 1 from url "{@url}"
	send "&7---------------------&bSegítség&7---------------------" to {_p}
	if "%{_ver}%" is "{@version}":
		send "&b<tooltip:&bA legfrissebb verzió van a rendszeren>punishment update check<reset>- &7 Verziószám ellenőrzése" to {_p}
	else:
		send "&b<tooltip:&bÚj verzió elérhető: &c%{_ver}%>/punishment update check<reset> - &7 Verziószám ellenőrzése" to {_p}
	send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p update log>/punishment update log<reset>- &7 Github frissítési napló" to {_p}
	send "&7-------------------------------------------------" to {_p}

#*************************#
#                         #
#         Loader          #
#                         #
#*************************#


on skript load:
	send "---------------------------------------------" to console
	send "{@prefix} &aPunishment skript - &aBetöltés..." to console
	send "{@prefix} &aPunishment skript - &aConfig betöltése..." to console
	send "{@prefix} &aPunishment skript - &aConfig betöltése sikeres!" to console
		#if yml file "{@listpath}" exists:
			# send "{@prefix} &aPunishment skript - &aStaffok listájának betöltése..." to console
		#	wait 1 tick
		#	load yaml "{@listpath}" as "{@listpath}"
		#	set {staff::*} to yaml list "Staffok" from "{@listpath}"
		#	send "{@prefix} &aPunishment skript - &aStaffok listájának betöltése sikeres" to console
		#else:
		#	createYMLFile("{@listpath}", "list: Staffok:Staffok neve")
		#	load yaml "{@listpath}" as "{@listpath}"
		#	set {staff::*} to yaml list "Staffok" from "{@listpath}"
	send "{@prefix} &aDiscord bot - betöltése..." to console
	#Discord
	login to "{@discordbot_TOKEN}" with name "{@discordbot_name}"
	mark bot named "{@discordbot_name}" watching "Skript code and stuff"
	
	send "{@prefix} &aDiscord bot - betöltése sikeres!" to console
	if {@checkUpdates} is true:
		set {_ver} to line 1 from url "{@url}"
		if "%{_ver}%" is "{@version}":
			send "{@prefix} &aNincs elérhető frissítés :)" to console
		else:
			send "{@prefix} &bFrissítés elérhető!" to console
			send "{@prefix} &bVerzió szám: &6%{_ver}%!" to console
			send "{@prefix} &bInnen tudod letöltni: {@updatelog}!" to console
	else:
		send "{@prefix} &cAz frissítő rendszer ki van kapcsolva!" to console
	send "{@prefix} &aPunishment skript - &aSikeres betöltés" to console
	send "---------------------------------------------" to console

on skript unload:
	send "---------------------------------------------" to console
	send "{@prefix} &aPunishment skript - &aLeállítása..." to console
	send "---------------------------------------------" to console


#*************************#
#                         #
#        Commands         #
#                         #
#*************************#

command /punishment [<text>] [<text>]:
	permission: {main_command_permission}
	permission message: {@prefix}{@permission_message}
	executable by: console and players
	aliases: /p, /punish
	trigger:
		# Help
		if arg-1 is "help":
			if executor is console:
				send "&7---------------------&bSegítség&7---------------------" to console
				send "&b/punishment help - &7 Ennek a menünek a megnyítása" to console
				send "&b/punishment reload - &7 Config/Skript újratötlése" to console
				send "&b/punishment update - &7 Frissítések" to console
				send "&b/punishment github - &7 Github" to console
				send "&b/ban [játékosnév] [idő] [ok] - &7Játékos kitiltása" to console
				send "&b/unban [játékosnév] [ok] - &7Játékos kitiltásának feloldása" to console
				send "&b/kick [játékosnév] [ok] - &7Játékos kirúgása" to console
				send "&b/mute [játékosnév] [idő] [ok] &r- &7Játékos némítása" to console
				send "&b/reprot [játékosnév] &r- &7Játékos jelentése" to console
				send "/reportdc [játékosnév] &r- &7Játékos jelentése discrodra" to console
				send "&7-------------------------------------------------" to console
			else:
				helpJSON(player)
		
		# reload
		
		else if arg-1 is "reload":
			set {_t} to now
			execute console command "/sk reload {@skript}"
			set {_diff} to difference between {_t} and now
			message "{@prefix} &aA skript újratöltve &b%{_diff}% &aidő alatt!"

		# Update
		
		else if arg-1 is "update":
			# version
			if arg-2 is "version":
				message "{@prefix} &aJelenlegi verzió: &6{@version}"
			# log
			else if arg-2 is "log" or "updatelog":
				message "{@prefix} &a{@updatelog}"
			# check
			else if arg-2 is "check" or "updatecheck":
				set {_ver} to line 1 from url "{@url}"
				if "%{_ver}%" isn't "{@version}":
					message "{@prefix} &cNem a legfrisseb verzió!"
					message "{@prefix} &6Innen tudod letölteni a legfríssebb verziót: &ahttps://github.com/InternalGaming02/BanGUI-Skript/releases"
				else:
					message "{@prefix} &aA legfrissebb verzió van a rendszeren!"			

			else if arg-2 isn't "version" or "log" or "updatelog" or "check" or "updatecheck" or "update" or "github":
				if executor is console:
					send "&7---------------------&bSegítség&7---------------------" to console
					send "&b/punishment update check &r- &7 Verziószám ellenőrzése" to console
					send "&b/punishment update log &r- &7 Github frissítési napló" to console
					send "&7-------------------------------------------------" to console
				else:
					updateHelp(player)
				
			# Github

			else if arg-2 is "github":
				message "{@prefix} &6https://github.com/InternalGaming02/BanGUI-Skript/releases"
				

		else if arg-1 isn't "help" or "reload" or "skriptreload" or "file" or "update":
			if executor is console:
				send "&7---------------------&bSegítség&7---------------------" to console
				send "&b/punishment help &r- &7 Ennek a menünek a megnyítása" to console
				send "&b/punishment reload &r- &7 Config újratötlése" to console
				send "&b/punishment skriptreload &r- &7 Skript újratötlése" to console
				send "&b/punishment file &r- &c Fájlok újragenerálása" to console
				send "&b/punishment update &r- &7 Frissítések" to console
				send "&b/punishment github &r- &7 Github" to console
				send "&b/ban [játékosnév] [idő] [ok] &r- &7Játékos kitiltása" to console
				send "&b/unban [játékosnév] [ok] &r- &7Játékos kitiltásának feloldása" to console
				send "&b/kick [játékosnév] [ok] &r- &7Játékos kirúgása" to console
				send "&b/mute [játékosnév] [idő] [ok] &r- &7Játékos némítása" to console
				send "&b/reprot [játékosnév] &r- &7Játékos jelentése" to console
				send "&b/reportdc [játékosnév] &r- &7Játékos jelentése discrodra" to console
				send "&7-------------------------------------------------" to console
			else:
				helpJSON(player)

#*************************#
#                         #
#      	    Ban           #
#                         #
#*************************#

command /ban [<offline player>] [<text>] [<timespan>]:
	permission: {@ban_permission}
	permission message: {@prefix} {@permission_message}
	executable by: console and players
	trigger:
		if arg-1 is set:
			if arg-2 is set:
				ban arg-1 due to arg-2
				kick arg-1 due to arg-2
				if arg-3 is set:
					send "a"
			else:
				ban arg-1 due to "{@forver_ban_message}"
				kick arg-1 due to "{@forver_ban_message}"
				
		else:
			message "Használat /ban [játékosnév] [ok] [idő]"

#*************************#
#                         #
#      	   Unban          #
#                         #
#*************************#

command /unban [<offline player>] [<text>]:
	permission: {@unban_permission}
	permission message: {@prefix} {@permission_message}
	executable by: console and players
	trigger:
		if arg-1 is set:
			if arg-2 is set:
				unban arg-1
			else:
				unban arg-1
		else:
			message "Használat /unban [játékosnév] [ok]"

#*************************#
#                         #
#      	   Kick           #
#                         #
#*************************#

command /kick [<offline player>] [<text>]:
	permission: {@kick_permission}
	permission message: {@prefix} {@permission_message}
	executable by: console and players
	trigger:
		if arg-1 is set:
			if arg-2 is set:
				kick arg-1 due to arg-2
			else:
				kick arg-1 due to "{@kick_message}"
		else:
			message "{@prefix} {@kick_usage}"
			
#*************************#
#                         #
#      	  Report          #
#                         #
#*************************#

function reportembed(reason : text, reported : player, reporter: player):
	make new embed:
		set title of embed to "%{_reported}%"
		set description of embed to "%{_reason}% miatt lett jelentve" #%nl%
		set author of embed to "%{_reporter}% küldte be"
		set color of embed to yellow
		set footer of embed to "Jelentve ekkor:"
		set footer icon of embed to "https://cdn.discordapp.com/attachments/611490783236849673/636950347360894976/NW_dc_logo.png"
		set timestamp of embed to now
	# send last created embed to the channel (text channel  with id"819185118056022029") with bot named "{@discordbot_name}"
	send the last made embed in channel with id "819185118056022029" with "{@discordbot_name}"

function report(reason : text, reported : player, reporter: player):
	loop all players:
		if {staff::*} contains loop-player:
			send "{@prefix} &a%{_reporter}% &bjelentette: &a%{_reported}% &bjátékost ezzel az indokkal: &c%{_reason}%" to loop-player

command /reportdc [<offline player>]:
	permission: nincs
	permission message: {@prefix} {@permission_message}
	executable by: console and players
	trigger:
		if arg-1 is set:
			if arg-1 is online:
				send "GUI" to player
			else:
				message "{@prefix} &6%arg-1% &cnem online!"
		else:
			message  "{@prefix} {használat}"
			
command /report [<offline player>]:
	permission: nincs
	permission message: {@prefix} {@permission_message}
	executable by: console and players
	trigger:
		if arg-1 is set:
			if arg-1 is online:
				send "GUI" to player
			else:
				message "{@prefix} &6%arg-1% &cnem online!"
		else:
			message  "{@prefix} {használat}"

on chat:
	if {reporting.%player%} is true:		
		set {reporting.customreport} to message 
		set {reporting.%player%} to false
		broadcast "staff chat: %{reporting.customreport}%"
		cancel event
	if {reporting.dc.%player%} is true:
		set {reporting.dc.customreport} to message 
		set {reporting.dc.%player%} to false
		reportembed("%{reporting.dc.customreport}%", {reporting.dc.reported}, {reporting.dc.reporter})
		cancel event