on load:
	# Messages
	set {options::prefix} to "&7[&cPunishment-&aDEV]"

	set {options::main_command_usage} to "&cHasználat: /punishmnet help"
	set {options::ban_usage} to " &cHasználat: /ban"
	set {options::unban_usage} to "&cHasználat: /unban"
	set {options::kick_usage} to "&cHasználat: /kick"

	set {options::permanent_ban_message} to "Bannolva lettél!"
	set {options::temporary_ban_message} to "Bannolva lettél!"
	set {options::unban_message} to "Unbannolva lettél!"
	set {options::kick_message} to "Kickelve lettél!"

	# Permissions
	set {options::permission_message} to "&cNincs jogod ehhez!"
	set {options::main_command_permission} to "punishment.use"
	set {options::ban_permission} to "punishment.ban"
	set {options::unban_permission} to "punishment.unban"
	set {options::kick_permission} to "punishment.kick"

	# Discord bot
	set {options::discordbot_name} to "SK-test"
	set {options::discordbot_TOKEN} to "NjEzMjc3NDU1NzA0MTI5NTU3.XVulIw.-pWF7vphhYEDrDJ4OPUxavJia5E"
	set {options::discordbot_watching} to "Szever lol"
	set {options::discordbot_reportChannel} to "829052591139848242"
	
	# Updater
	set {options::version} to "1.0.3"
	set {options::url} to "https://pastebin.com/raw/RbzMPk3L"
	# Updater on/off
	set {options::checkUpdates} to "false"
	
	#Updatelog
	set {options::updatelog} to "https://github.com/InternalGaming02/BanGUI-Skript/releases"

# Setter
function getFromConfig(configValue: text ) :: text:
	return {options::%{_configValue}%}