#Start-up

on skript load:
    set {prefix} to getFromConfig("prefix")
    set {url} to getFromConfig("url")

    send "---------------------------------------------" to console
    send "%{prefix}% &aPunishment skript Functions - &aBetöltés..." to console
    send "%{prefix}% &aPunishment skript Functions - &aSikeres betöltés!" to console
    send "---------------------------------------------" to console

# Reload

on load:
    set {prefix} to getFromConfig("prefix")
    set {url} to getFromConfig("url")

#Functions
function getVersionFromUrl(url: text) :: text:
    send request to {_url}
    set {_resp} to the last http response
    set {_version} to {_resp}'s body
    return {_version}


function punishmentHelpForPlayer(commandSender: executor):
    if {_commandSender} is player:
        send "&7---------------------&bSegítség&7---------------------" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p help>/punishment help<reset> - &7Ennek a menünek a megnyítása" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p reload>/punishment reload<reset> - &7Config/Skript újratötlése" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p update>/punishment update<reset> - &7Frissítések" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><link:https://github.com/InternalGaming02/BanGUI-Skript>/punishment github<reset>- &7Github" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/ban >/ban [játékosnév] [idő] [ok]<reset>- &7Játékos kitiltása" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/unban>/unban [játékosnév] [ok]<reset> - &7Játékos kitiltásának feloldása" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/kick>/kick [játékosnév] [ok]<reset> - &7Játékos kirúgása" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/mute>/mute [játékosnév] [idő] [ok]<reset> - &7Játékos némítása" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/report>/report [játékosnév]<reset> - &7Játékos jelentése" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/reportdc >/reportdc [játékosnév]<reset>- &7Játékos jelentése Discord-on" to {_commandSender}
        send "&7-------------------------------------------------" to {_commandSender}
    else:
        send "&7---------------------&bSegítség&7---------------------" to {_commandSender}
        send "&b/punishment help - &7Ennek a menünek a megnyítása" to {_commandSender}
        send "&b/punishment reload - &7Config/Skript újratötlése" to {_commandSender}
        send "&b/punishment update - &7Frissítések" to {_commandSender}
        send "&b/punishment github - &7Github" to {_commandSender}
        send "&b/ban [játékosnév] [idő] [ok] - &7Játékos kitiltása" to {_commandSender}
        send "&b/unban [játékosnév] [ok] - &7Játékos kitiltásának feloldása" to {_commandSender}
        send "&b/kick [játékosnév] [ok] - &7Játékos kirúgása" to {_commandSender}
        send "&b/mute [játékosnév] [idő] [ok] &r- &7Játékos némítása" to {_commandSender}
        send "&b/reprot [játékosnév] &r- &7Játékos jelentése" to {_commandSender}
        send "&b/reportdc [játékosnév] &r- &7Játékos jelentése discrodra" to {_commandSender}
        send "&7-------------------------------------------------" to {_commandSender}

function punishmentUpdateHelpForPlayer(commandSender: executor):
	
    if {_commandExecutor} is player:
        set {_ver} to getVersionFromUrl("%{url}%")
        send "&7---------------------&bSegítség&7---------------------" to {_commandSender}
        if "%{_ver}%" is "%{version}%":
            send "&b<tooltip:&bA legfrissebb verzió van a rendszeren>punishment update check<reset>- &7Verziószám ellenőrzése" to {_commandSender}
        else:
            send "&b<tooltip:&bÚj verzió elérhető: &c%{_ver}%>/punishment update check<reset> - &7Verziószám ellenőrzése" to {_commandSender}
        send "&b<tooltip:&bKatt a parancs futtatásáért><suggest command:/p update log>/punishment update log<reset>- &7Github frissítési napló" to {_commandSender}
        send "&7-------------------------------------------------" to {_commandSender}
    else:
        send "&7---------------------&bSegítség&7---------------------" to {_commandSender}
        send "&b/punishment update check &r- &7Verziószám ellenőrzése" to {_commandSender}
        send "&b/punishment update log &r- &7Github frissítési napló" to {_commandSender}
        send "&7-------------------------------------------------" to {_commandSender}