# Start-up

on skript load:
	set {prefix} to getFromConfig("prefix")
	send "---------------------------------------------" to console
	send "%{prefix}% &aPunishment skript DISCORD - &aBetöltés..." to console

	set {permission_message} to getFromConfig("permission_message")
	set {discordbot_TOKEN} to getFromConfig("discordbot_TOKEN")
	set {discordbot_name} to getFromConfig("discordbot_name")
	set {discordbot_watching} to getFromConfig("discordbot_watching")
	set {discordbot_reportChannel} to getFromConfig("discordbot_reportChannel")

	login to "%{discordbot_TOKEN}%" with name "%{discordbot_name}%"
	mark bot named "%{discordbot_name}%" watching "%{discordbot_watching}%"
	send "%{prefix}% &aPunishment skript DISCORD - &aSikeres betöltés!" to console
	send "---------------------------------------------" to console

# Reload

on load:
	set {prefix} to getFromConfig("prefix")
	set {permission_message} to getFromConfig("permission_message")
	set {discordbot_TOKEN} to getFromConfig("discordbot_TOKEN")
	set {discordbot_name} to getFromConfig("discordbot_name")
	set {discordbot_watching} to getFromConfig("discordbot_watching")
	set {discordbot_reportChannel} to getFromConfig("discordbot_reportChannel")
	if bot "%{discordbot_name}%" is not loaded:
		login to "%{discordbot_TOKEN}%" with name "%{discordbot_name}%"
	mark bot named "%{discordbot_name}%" watching "%{discordbot_watching}%"


# Report

function createReportEmbed(reason : text, reported : player, reporter: player, channelID: text, botName: text):
    make new embed:
        set title of embed to "%{_reported}%"
        set description of embed to "%{_reason}% miatt lett jelentve"
        set author of embed to "%{_reporter}% küldte be"
        set color of embed to yellow
        set footer of embed to "Jelentve ekkor:"
        set footer icon of embed to "https://cdn.discordapp.com/attachments/611490783236849673/636950347360894976/NW_dc_logo.png"
        set timestamp of embed to now
    send the last generated embed to text channel with id "%{_channelID}%" with bot named "%{_botName}%"

function report(reason : text, reported : player, reporter: player):
	loop all players:
		if {staff::*} contains loop-player:
			send "%{prefix}% &a%{_reporter}% &bjelentette: &a%{_reported}% &bjátékost ezzel az indokkal: &c%{_reason}%" to loop-player

# Commands

command /reportdc [<offline player>] [<text>]:
	permission: nincs
	permission message: "%{prefix}% %{permission_message}%"
	executable by: players
	trigger:
		if arg-1 is set:
			if arg-1 is online:
				if arg-2 is set:
					createReportEmbed(arg-2, arg-1, player, {discordbot_reportChannel}, {discordbot_name})
			else:
				message "%{prefix}% &6%arg-1% &cnem online!"
		else:
			message  "%{prefix}% használat"
			
command /report [<offline player>]:
	permission: nincs
	permission message: "%{prefix}% %{permission_message}%"
	executable by: console and players
	trigger:
		if arg-1 is set:
			if arg-1 is online:
				send "GUI" to player
			else:
				message "%{prefix}% &6%arg-1% &cnem online!"
		else:
			message  "%{prefix}% használat"
